In [67]:
# load library
import numpy as np

In [68]:
# Initialise four random arrays
x = np.random.rand(30,1)
y = np.random.rand(30,1)
z = np.random.rand(30,1)
w = np.random.rand(1,30)

In [69]:
# list of variables
matrices = [x,y,z,w]

In [70]:
# Check shapes of matrices
for matrix in matrices:
    print(f'Matrix: {matrix.shape}')

Matrix: (30, 1)
Matrix: (30, 1)
Matrix: (30, 1)
Matrix: (1, 30)


In [71]:
# reconstruct input data
a = list()
for index in range(0,30,1):
    a.append([x.item(index), y.item(index), z.item(index)])

In [74]:
# convert list to np array
a = np.array(a)
print(a[:10])

[[0.58224396 0.68726067 0.60650871]
 [0.35801242 0.76069717 0.02605956]
 [0.23840535 0.68356737 0.59920578]
 [0.6953972  0.8322601  0.955408  ]
 [0.99914321 0.78339009 0.46568704]
 [0.69464879 0.41142565 0.87953126]
 [0.06095309 0.87666737 0.89821209]
 [0.99566639 0.98366096 0.99431337]
 [0.37346557 0.02873331 0.78336726]
 [0.95770301 0.17488446 0.40742799]]


In [54]:
# reconstruct output data
b = np.array(w)

In [55]:
b.shape

(1, 30)

In [56]:
# solve set of simultaneous equations
x = np.linalg.solve(a,b)

LinAlgError: Last 2 dimensions of the array must be square

In [63]:
import numpy as np
a = np.array([[3,1,3], [1,2,3],[9,8,3]])
b = np.array([9,8,3])
x = np.linalg.solve(a, b)
x


array([ 0.05, -0.9 ,  3.25])

In [64]:
a.shape

(3, 3)

In [65]:
b.shape

(3,)